version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily


  - package-ecosystem: npm
    directory: /.open-next/server-functions/default/.next
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /.open-next/server-functions/default
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
